const mongoose = require('mongoose');

const importantDateSchema = new mongoose.Schema(
  {
    edition: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Edition',
      required: [true, 'Edition is required'],
    },
    label: { type: String, required: [true, 'Label is required'], trim: true },
    date: { type: Date, required: [true, 'Date is required'] },
    category: {
      type: String,
      enum: ['abstracts', 'registrations', 'congress', 'other'],
      default: 'other',
    },
    isHighlighted: { type: Boolean, default: false },
    displayOrder: { type: Number, default: 0 },

    // Set when this entry mirrors a pricing tier's deadline. Such entries are
    // created, updated and removed alongside their tier rather than by hand.
    pricingTier: { type: mongoose.Schema.Types.ObjectId, ref: 'PricingTier' },
    autoGenerated: { type: Boolean, default: false },
  },
  { timestamps: true }
);

module.exports = mongoose.model('ImportantDate', importantDateSchema);
