const PricingTier = require('../models/PricingTier');
const ImportantDate = require('../models/ImportantDate');

const TIER_ORDER = ['early_bird', 'mid_term', 'on_spot'];
const TIER_LABELS = {
  early_bird: 'Early Bird',
  mid_term: 'Mid Term',
  on_spot: 'On Spot',
};

const tierName = (tier) => tier.label || TIER_LABELS[tier.name] || tier.name;

/** endDate wins; `deadline` is the legacy field kept for older rows. */
const endOf = (tier) => tier.endDate || tier.deadline || null;

/** Tiers in schedule order: by window end, then by the canonical tier sequence. */
function sortTiers(tiers) {
  return [...tiers].sort((a, b) => {
    const ae = endOf(a);
    const be = endOf(b);
    if (ae && be && ae.getTime() !== be.getTime()) return ae - be;
    if (ae && !be) return -1;
    if (!ae && be) return 1;
    const ai = TIER_ORDER.indexOf(a.name);
    const bi = TIER_ORDER.indexOf(b.name);
    return (ai === -1 ? 99 : ai) - (bi === -1 ? 99 : bi);
  });
}

/**
 * Decides which tier should currently be open for one edition and writes the
 * result, so an expired tier stands down and the next one takes over without
 * anyone touching the admin panel.
 *
 * A tier opens when the previous one closes unless it carries its own
 * startDate. The open tier is the earliest one that has not yet expired and
 * has already started.
 *
 * Tiers with `autoActivate: false` are left exactly as the admin set them, and
 * their presence suppresses automatic switching for that edition so the two
 * modes never fight over the same edition.
 */
async function syncEditionWindows(editionId) {
  if (!editionId) return;

  const tiers = await PricingTier.find({ edition: editionId });
  if (!tiers.length) return;

  // Any manual tier means this edition is admin-controlled
  if (tiers.some((t) => t.autoActivate === false)) return;

  const ordered = sortTiers(tiers);
  const now = Date.now();

  let openId = null;
  let prevEnd = null;

  for (const tier of ordered) {
    const end = endOf(tier);
    const start = tier.startDate || prevEnd;

    const started = !start || start.getTime() <= now;
    const expired = end ? end.getTime() < now : false;

    if (!expired && started && !openId) openId = String(tier._id);
    prevEnd = end || prevEnd;
  }

  const ops = ordered
    .map((tier) => ({ tier, shouldBeActive: String(tier._id) === openId }))
    .filter(({ tier, shouldBeActive }) => Boolean(tier.isActive) !== shouldBeActive)
    .map(({ tier, shouldBeActive }) => ({
      updateOne: { filter: { _id: tier._id }, update: { $set: { isActive: shouldBeActive } } },
    }));

  if (ops.length) await PricingTier.bulkWrite(ops);
}

/** Runs the window sync across every edition that has pricing tiers. */
async function syncAllWindows() {
  const editionIds = await PricingTier.distinct('edition');
  for (const id of editionIds) await syncEditionWindows(id);
}

/**
 * Mirrors a tier's deadline into Important Dates so the public deadline list
 * stays in step with pricing. One auto entry per tier, created on demand and
 * updated in place afterwards.
 */
async function syncTierImportantDate(tier) {
  if (!tier) return;
  const date = endOf(tier);
  const existing = await ImportantDate.findOne({ pricingTier: tier._id, autoGenerated: true });

  // No deadline left to mirror: drop the generated entry
  if (!date) {
    if (existing) await existing.deleteOne();
    return;
  }

  const label = `${tierName(tier)} Registration Deadline`;

  if (existing) {
    existing.label = label;
    existing.date = date;
    existing.edition = tier.edition;
    existing.category = 'registrations';
    await existing.save();
    return;
  }

  await ImportantDate.create({
    edition: tier.edition,
    label,
    date,
    category: 'registrations',
    pricingTier: tier._id,
    autoGenerated: true,
  });
}

/** Removes the generated Important Date when its tier goes away. */
async function removeTierImportantDate(tierId) {
  if (!tierId) return;
  await ImportantDate.deleteMany({ pricingTier: tierId, autoGenerated: true });
}

module.exports = {
  endOf,
  sortTiers,
  syncEditionWindows,
  syncAllWindows,
  syncTierImportantDate,
  removeTierImportantDate,
};
